## TODO: Typecheck arguments

# ComputerCraft: Tweaked
[selene]
base = "lua51"
name = "cctweaked"

[_HOST]
property = true

[_CC_DEFAULT_SETTINGS]
property = true

[[write.args]]
type = "any"

[[printError.args]]
type = "any"

[[read.args]]
type = "any"

[colors.white]
property = true

[colors.orange]
property = true

[colors.magenta]
property = true

[colors.lightBlue]
property = true

[colors.yellow]
property = true

[colors.lime]
property = true

[colors.pink]
property = true

[colors.gray]
property = true

[colors.lightGray]
property = true

[colors.cyan]
property = true

[colors.purple]
property = true

[colors.blue]
property = true

[colors.brown]
property = true

[colors.green]
property = true

[colors.red]
property = true

[colors.black]
property = true

[[commands.native.args]]
type = "any"

[[commands.async.args]]
type = "any"

[[commands.exec.args]]
type = "any"

[[commands.execAsync.args]]
type = "any"

[[commands.list.args]]
type = "any"

[[commands.getBlockPosition.args]]
type = "any"

[[commands.getBlockInfos.args]]
type = "any"

[[commands.getBlockInfo.args]]
type = "any"

[[disk.isPresent.args]]
type = "any"

[[disk.getLabel.args]]
type = "any"

[[disk.setLabel.args]]
type = "any"

[[disk.hasData.args]]
type = "any"

[[disk.getMountPath.args]]
type = "any"

[[disk.hasAudio.args]]
type = "any"

[[disk.getAudioTitle.args]]
type = "any"

[[disk.playAudio.args]]
type = "any"

[[disk.stopAudio.args]]
type = "any"

[[disk.eject.args]]
type = "any"

[[disk.getID.args]]
type = "any"

[[fs.isDriveRoot.args]]
type = "any"

[[fs.complete.args]]
type = "any"

[[fs.list.args]]
type = "any"

[[fs.combine.args]]
type = "any"

[[fs.getName.args]]
type = "any"

[[fs.getDir.args]]
type = "any"

[[fs.getSize.args]]
type = "any"

[[fs.exists.args]]
type = "any"

[[fs.isDir.args]]
type = "any"

[[fs.isReadOnly.args]]
type = "any"

[[fs.makeDir.args]]
type = "any"

[[fs.move.args]]
type = "any"

[[fs.copy.args]]
type = "any"

[[fs.delete.args]]
type = "any"

[[fs.open.args]]
type = "any"

[[fs.getDrive.args]]
type = "any"

[[fs.getFreeSpace.args]]
type = "any"

[[fs.find.args]]
type = "any"

[[fs.getCapacity.args]]
type = "any"

[[fs.attributes.args]]
type = "any"

[gps.CHANNEL_GPS]
property = true

[[gps.locate.args]]
type = "any"

[[help.path.args]]
type = "any"

[[help.setPath.args]]
type = "any"

[[help.lookup.args]]
type = "any"

[[help.topics.args]]
type = "any"

[[help.completeTopic.args]]
type = "any"

[[http.request.args]]
type = "any"

[[http.get.args]]
type = "any"

[[http.post.args]]
type = "any"

[[http.checkURLAsync.args]]
type = "any"

[[http.checkURL.args]]
type = "any"

[[http.websocket.args]]
type = "any"

[[http.websocketAsync.args]]
type = "any"

[io.stdin]
property = true

[io.stdout]
property = true

[io.stderr]
property = true

[[io.close.args]]
type = "any"

[[io.flush.args]]
type = "any"

[[io.input.args]]
type = "any"

[[io.lines.args]]
type = "any"

[[io.open.args]]
type = "any"

[[io.output.args]]
type = "any"

[[io.read.args]]
type = "any"

[[io.type.args]]
type = "any"

[[io.write.args]]
type = "any"

[[keys.getName.args]]
type = "any"

[[os.pullEvent.args]]
type = "any"

[[os.pullEventRaw.args]]
type = "any"

[[os.sleep.args]]
type = "any"

[[os.version.args]]
type = "any"

[[os.run.args]]
type = "any"

[[os.queueEvent.args]]
type = "any"

[[os.startTimer.args]]
type = "any"

[[os.cancelTimer.args]]
type = "any"

[[os.setAlarm.args]]
type = "any"

[[os.cancelAlarm.args]]
type = "any"

[[os.shutdown.args]]
type = "any"

[[os.reboot.args]]
type = "any"

[[os.getComputerID.args]]
type = "any"

[[os.computerID.args]]
type = "any"

[[os.getComputerLabel.args]]
type = "any"

[[os.computerLabel.args]]
type = "any"

[[os.setComputerLabel.args]]
type = "any"

[[os.day.args]]
type = "any"

[[paintutils.parseImage.args]]
type = "any"

[[paintutils.loadImage.args]]
type = "any"

[[paintutils.drawPixel.args]]
type = "any"

[[paintutils.drawLine.args]]
type = "any"

[[paintutils.drawBox.args]]
type = "any"

[[paintutils.drawFilledBox.args]]
type = "any"

[[paintutils.drawImage.args]]
type = "any"

[[parallel.waitForAny.args]]
type = "any"

[[parallel.waitForAll.args]]
type = "any"

[[peripheral.getNames.args]]
type = "any"

[[peripheral.isPresent.args]]
type = "any"

[[peripheral.getType.args]]
type = "any"

[[peripheral.getMethods.args]]
type = "any"

[[peripheral.getName.args]]
type = "any"

[[peripheral.call.args]]
type = "any"

[[peripheral.wrap.args]]
type = "any"

[[peripheral.find.args]]
type = "any"

[[pocket.equipBack.args]]
type = "any"

[[pocket.unequipBack.args]]
type = "any"

[rednet.CHANNEL_BROADCAST]
property = true

[rednet.CHANNEL_REPEAT]
property = true

[[rednet.open.args]]
type = "any"

[[rednet.close.args]]
type = "any"

[[rednet.isOpen.args]]
type = "any"

[[rednet.send.args]]
type = "any"

[[rednet.broadcast.args]]
type = "any"

[[rednet.receive.args]]
type = "any"

[[rednet.host.args]]
type = "any"

[[rednet.unhost.args]]
type = "any"

[[rednet.lookup.args]]
type = "any"

[[rednet.run.args]]
type = "any"

[[redstone.getSides.args]]
type = "any"

[[redstone.setOutput.args]]
type = "any"

[[redstone.getOutput.args]]
type = "any"

[[redstone.getInput.args]]
type = "any"

[[redstone.setAnalogOutput.args]]
type = "any"

[[redstone.setAnalogueOutput.args]]
type = "any"

[[redstone.getAnalogOutput.args]]
type = "any"

[[redstone.getAnalogueOutput.args]]
type = "any"

[[redstone.getAnalogInput.args]]
type = "any"

[[redstone.getAnalogueInput.args]]
type = "any"

[[redstone.setBundledOutput.args]]
type = "any"

[[redstone.getBundledOutput.args]]
type = "any"

[[redstone.getBundledInput.args]]
type = "any"

[[redstone.testBundledInput.args]]
type = "any"

[[settings.define.args]]
type = "any"

[[settings.undefine.args]]
type = "any"

[[settings.set.args]]
type = "any"

[[settings.get.args]]
type = "any"

[[settings.getDetails.args]]
type = "any"

[[settings.unset.args]]
type = "any"

[[settings.clear.args]]
type = "any"

[[settings.getNames.args]]
type = "any"

[[settings.load.args]]
type = "any"

[[settings.save.args]]
type = "any"

[[shell.execute.args]]
type = "any"

[[shell.run.args]]
type = "any"

[[shell.exit.args]]
type = "any"

[[shell.dir.args]]
type = "any"

[[shell.setDir.args]]
type = "any"

[[shell.path.args]]
type = "any"

[[shell.setPath.args]]
type = "any"

[[shell.resolve.args]]
type = "any"

[[shell.resolveProgram.args]]
type = "any"

[[shell.programs.args]]
type = "any"

[[shell.complete.args]]
type = "any"

[[shell.completeProgram.args]]
type = "any"

[[shell.setCompletionFunction.args]]
type = "any"

[[shell.getCompletionInfo.args]]
type = "any"

[[shell.getRunningProgram.args]]
type = "any"

[[shell.setAlias.args]]
type = "any"

[[shell.clearAlias.args]]
type = "any"

[[shell.aliases.args]]
type = "any"

[[shell.openTab.args]]
type = "any"

[[shell.switchTab.args]]
type = "any"

[[term.nativePaletteColour.args]]
type = "any"

[[term.nativePaletteColor.args]]
type = "any"

[[term.write.args]]
type = "any"

[[term.scroll.args]]
type = "any"

[[term.getCursorPos.args]]
type = "any"

[[term.setCursorPos.args]]
type = "any"

[[term.getCursorBlink.args]]
type = "any"

[[term.setCursorBlink.args]]
type = "any"

[[term.getSize.args]]
type = "any"

[[term.clear.args]]
type = "any"

[[term.clearLine.args]]
type = "any"

[[term.getTextColour.args]]
type = "any"

[[term.getTextColor.args]]
type = "any"

[[term.setTextColour.args]]
type = "any"

[[term.setTextColor.args]]
type = "any"

[[term.getBackgroundColour.args]]
type = "any"

[[term.getBackgroundColor.args]]
type = "any"

[[term.setBackgroundColour.args]]
type = "any"

[[term.setBackgroundColor.args]]
type = "any"

[[term.isColour.args]]
type = "any"

[[term.isColor.args]]
type = "any"

[[term.blit.args]]
type = "any"

[[term.setPaletteColour.args]]
type = "any"

[[term.getPaletteColour.args]]
type = "any"

[[term.getPaletteColor.args]]
type = "any"

[[term.redirect.args]]
type = "any"

[[term.current.args]]
type = "any"

[[term.native.args]]
type = "any"

[textutils.empty_json_array]
property = true

[textutils.json_null]
property = true

[[textutils.slowWrite.args]]
type = "any"

[[textutils.slowPrint.args]]
type = "any"

[[textutils.formatTime.args]]
type = "any"

[[textutils.pagedPrint.args]]
type = "any"

[[textutils.tabulate.args]]
type = "any"

[[textutils.pagedTabulate.args]]
type = "any"

[[textutils.serialize.args]]
type = "any"

[[textutils.seralise.args]]
type = "any"

[[textutils.unserialize.args]]
type = "any"

[[textutils.unserialise.args]]
type = "any"

[[textutils.serializeJSON.args]]
type = "any"

[[textutils.serialiseJSON.args]]
type = "any"

[[textutils.unserializeJSON.args]]
type = "any"

[[textutils.unserialiseJSON.args]]
type = "any"

[[textutils.urlEncode.args]]
type = "any"

[[textutils.complete.args]]
type = "any"

[[turtle.forward.args]]
type = "any"

[[turtle.back.args]]
type = "any"

[[turtle.up.args]]
type = "any"

[[turtle.down.args]]
type = "any"

[[turtle.turnLeft.args]]
type = "any"

[[turtle.turnRight.args]]
type = "any"

[[turtle.dig.args]]
type = "any"

[[turtle.digUp.args]]
type = "any"

[[turtle.digDown.args]]
type = "any"

[[turtle.place.args]]
type = "any"

[[turtle.placeUp.args]]
type = "any"

[[turtle.placeDown.args]]
type = "any"

[[turtle.drop.args]]
type = "any"

[[turtle.dropUp.args]]
type = "any"

[[turtle.dropDown.args]]
type = "any"

[[turtle.select.args]]
type = "any"

[[turtle.getItemCount.args]]
type = "any"

[[turtle.getItemSpace.args]]
type = "any"

[[turtle.detect.args]]
type = "any"

[[turtle.detectUp.args]]
type = "any"

[[turtle.detectDown.args]]
type = "any"

[[turtle.compare.args]]
type = "any"

[[turtle.compareUp.args]]
type = "any"

[[turtle.compareDown.args]]
type = "any"

[[turtle.attack.args]]
type = "any"

[[turtle.attackUp.args]]
type = "any"

[[turtle.attackDown.args]]
type = "any"

[[turtle.suck.args]]
type = "any"

[[turtle.suckUp.args]]
type = "any"

[[turtle.suckDown.args]]
type = "any"

[[turtle.getFuelLevel.args]]
type = "any"

[[turtle.refuel.args]]
type = "any"

[[turtle.compareTo.args]]
type = "any"

[[turtle.transferTo.args]]
type = "any"

[[turtle.getSelectedSlot.args]]
type = "any"

[[turtle.getFuelLimit.args]]
type = "any"

[[turtle.equipLeft.args]]
type = "any"

[[turtle.equipRight.args]]
type = "any"

[[turtle.inspect.args]]
type = "any"

[[turtle.inspectUp.args]]
type = "any"

[[turtle.inspectDown.args]]
type = "any"

[[turtle.getItemDetail.args]]
type = "any"

[[turtle.craft.args]]
type = "any"

[[vector.new.args]]
type = "any"

[[window.create.args]]
type = "any"